version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  celery:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: celery -A social_media_api worker -l info
    env_file:
      - .env
    depends_on:
      - app
      - redis
      - db

  redis:
    image: redis:alpine

  db:
    image: postgres:16-alpine
    env_file:
      - .env
